const { pool } = require('./db.pg');

const initPostgres = async () => {
  const client = await pool.connect();
  try {
    console.log('PostgreSQL 테이블 및 뷰 동기화 시작 (TimescaleDB 최적화 및 KST 보정)...');

    // 1. 기본 테이블 생성 (Transaction 사용 가능)
    await client.query('BEGIN');

    // [설정] DB 기본 타임존 KST 고정
    await client.query(`ALTER DATABASE ${process.env.DB_NAME || 'alliothub'} SET timezone TO 'Asia/Seoul';`);
    await client.query(`SET TIME ZONE 'Asia/Seoul';`);

    await client.query(`CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;`);

    await client.query(`
      CREATE TABLE IF NOT EXISTS public.members (
        member_id SERIAL PRIMARY KEY,
        username CHARACTER VARYING(50) NOT NULL UNIQUE,
        password CHARACTER VARYING(255) NOT NULL,
        created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        worker CHARACTER VARYING(100),
        "phoneNumber" CHARACTER VARYING(25),
        is_admin BOOLEAN DEFAULT FALSE
      );

      CREATE TABLE IF NOT EXISTS public.imei_meta (
        imei TEXT PRIMARY KEY,
        address TEXT, sido TEXT, sigungu TEXT,
        lat DOUBLE PRECISION, lon DOUBLE PRECISION,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        energy_hex TEXT, type_hex TEXT, multi_count INTEGER,
        worker TEXT, "phoneNumber" TEXT
      );

      CREATE TABLE IF NOT EXISTS public.facility_info (
        rtuimei TEXT PRIMARY KEY,
        module_capacity TEXT, install_date DATE, monitor_start DATE,
        project_name TEXT, contractor TEXT, as_contact TEXT, image_url TEXT,
        created_by INTEGER REFERENCES public.members(member_id),
        updated_by INTEGER REFERENCES public.members(member_id),
        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS public.facility_maintenance (
        rtuimei TEXT PRIMARY KEY, last_inspection DATE, as_notes TEXT,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS public.facility_maintenance_history (
        id SERIAL PRIMARY KEY, rtuimei TEXT NOT NULL,
        maintenance_date DATE, as_notes TEXT,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS public.energy_nationwide_cache (
        key TEXT PRIMARY KEY, payload JSONB NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS public.django_migrations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        app CHARACTER VARYING(255) NOT NULL,
        name CHARACTER VARYING(255) NOT NULL,
        applied TIMESTAMP WITH TIME ZONE NOT NULL
      );

      CREATE TABLE IF NOT EXISTS public.auth_login_attempts (
        id BIGSERIAL PRIMARY KEY,
        member_id INTEGER REFERENCES public.members(member_id) ON DELETE SET NULL,
        username CHARACTER VARYING(50), success BOOLEAN NOT NULL,
        ip INET, user_agent TEXT, reason TEXT,
        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS public.auth_password_reset (
        id BIGSERIAL PRIMARY KEY,
        member_id BIGINT REFERENCES public.members(member_id) ON DELETE CASCADE,
        token_hash TEXT NOT NULL, expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
        used_at TIMESTAMP WITH TIME ZONE,
        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS public.auth_password_history (
        id SERIAL PRIMARY KEY,
        member_id INTEGER REFERENCES public.members(member_id) ON DELETE CASCADE,
        password_hash TEXT NOT NULL, created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS public.log_rtureceivelog (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
        time TIMESTAMP WITH TIME ZONE NOT NULL,
        "deviceModel" CHARACTER VARYING(5) NOT NULL,
        "msgType" CHARACTER VARYING(1) NOT NULL,
        "seqSendTime" TIME WITHOUT TIME ZONE NOT NULL,
        "businessId" INTEGER, "serviceId" INTEGER,
        "opMode" CHARACTER VARYING(10) NOT NULL,
        "multiId" SMALLINT NOT NULL,
        "bodyLength" INTEGER NOT NULL,
        "bodyOptionId" SMALLINT NOT NULL,
        body TEXT,
        "rtuImei" CHARACTER VARYING(23) NOT NULL
      );

      CREATE TABLE IF NOT EXISTS public.log_remssendlog (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        time TIMESTAMP WITH TIME ZONE NOT NULL,
        "multiId" SMALLINT NOT NULL,
        cid CHARACTER VARYING(25) NOT NULL,
        body TEXT,
        result CHARACTER VARYING(1) NOT NULL,
        error TEXT,
        "rtuImei" CHARACTER VARYING(23) NOT NULL
      );

      CREATE INDEX IF NOT EXISTS "log_remssendlog_cid_42d45c5b" ON public.log_remssendlog (cid);
      CREATE INDEX IF NOT EXISTS "log_remssendlog_rtuImei_38fe98eb" ON public.log_remssendlog ("rtuImei");
      CREATE INDEX IF NOT EXISTS "log_remssendlog_time_84716e9d" ON public.log_remssendlog ("time");
    `);

    await client.query('COMMIT');
    console.log('기본 테이블 생성 완료.');

    // 2. 하이퍼테이블 설정 (Transaction 외부 권장)
    try {
      await client.query(`SELECT create_hypertable('public.log_rtureceivelog', 'time', if_not_exists => TRUE);`);
      await client.query(`SELECT create_hypertable('public.log_remssendlog', 'time', if_not_exists => TRUE);`);
      console.log('하이퍼테이블 설정 완료.');
    } catch (e) {
      console.log('하이퍼테이블 설정 건너뜀 (이미 존재함).');
    }

    // --- 집계 뷰 생성 전 기존 뷰 삭제 (에러 방지용) ---
    console.log('기존 집계 뷰 초기화 중...');
    await client.query(`DROP MATERIALIZED VIEW IF EXISTS log_rtureceivelog_daily CASCADE;`);
    await client.query(`DROP MATERIALIZED VIEW IF EXISTS log_rtureceivelog_hourly CASCADE;`);

    // 3. 지속적 집계 뷰 (Daily) - time_bucket 수정 (AT TIME ZONE 제거)
    console.log('지속적 집계 뷰(Daily) 생성 중...');
    await client.query(`
      CREATE MATERIALIZED VIEW log_rtureceivelog_daily
      WITH (timescaledb.continuous) AS
      SELECT 
          time_bucket('1 day', "time") AS day,
          "rtuImei",
          split_part(body, ' ', 2) AS energy_hex,
          split_part(body, ' ', 3) AS type_hex,
          split_part(body, ' ', 4) AS multi_hex,
          max(CASE WHEN split_part(body, ' ', 5) = '00' THEN (('x' || encode(substring(decode(replace(body, ' ', ''), 'hex'),
              CASE
                  WHEN split_part(body, ' ', 2) = '01' AND split_part(body, ' ', 3) = '01' THEN 22
                  WHEN split_part(body, ' ', 2) = '01' AND split_part(body, ' ', 3) = '02' THEN 34
                  WHEN split_part(body, ' ', 2) = '02' AND split_part(body, ' ', 3) = '01' THEN 18
                  WHEN split_part(body, ' ', 2) = '02' AND split_part(body, ' ', 3) = '02' THEN 14
                  WHEN split_part(body, ' ', 2) = '03' AND split_part(body, ' ', 3) = '01' THEN 16
                  WHEN split_part(body, ' ', 2) = '03' AND split_part(body, ' ', 3) = '02' THEN 14
                  ELSE 22
              END, 8), 'hex'))::bit(64)::bigint) ELSE NULL END) AS max_wh,
          min(CASE WHEN split_part(body, ' ', 5) = '00' THEN (('x' || encode(substring(decode(replace(body, ' ', ''), 'hex'),
              CASE
                  WHEN split_part(body, ' ', 2) = '01' AND split_part(body, ' ', 3) = '01' THEN 22
                  WHEN split_part(body, ' ', 2) = '01' AND split_part(body, ' ', 3) = '02' THEN 34
                  WHEN split_part(body, ' ', 2) = '02' AND split_part(body, ' ', 3) = '01' THEN 18
                  WHEN split_part(body, ' ', 2) = '02' AND split_part(body, ' ', 3) = '02' THEN 14
                  WHEN split_part(body, ' ', 2) = '03' AND split_part(body, ' ', 3) = '01' THEN 16
                  WHEN split_part(body, ' ', 2) = '03' AND split_part(body, ' ', 3) = '02' THEN 14
                  ELSE 22
              END, 8), 'hex'))::bit(64)::bigint) ELSE NULL END) AS min_wh
      FROM public.log_rtureceivelog
      WHERE split_part(body, ' ', 5) IN ('00', '39')
      GROUP BY day, "rtuImei", energy_hex, type_hex, multi_hex;
    `);
    await client.query(`ALTER MATERIALIZED VIEW log_rtureceivelog_daily SET (timescaledb.materialized_only = false);`);

    // 4. 지속적 집계 뷰 (Hourly) - time_bucket 수정 (AT TIME ZONE 제거)
    console.log('지속적 집계 뷰(Hourly) 생성 중...');
    await client.query(`
      CREATE MATERIALIZED VIEW log_rtureceivelog_hourly
      WITH (timescaledb.continuous) AS
      SELECT 
          time_bucket('1 hour', "time") AS hour,
          "rtuImei",
          split_part(body, ' ', 2) AS energy_hex,
          split_part(body, ' ', 3) AS type_hex,
          split_part(body, ' ', 4) AS multi_hex,
          max(CASE WHEN split_part(body, ' ', 5) = '00' THEN (('x' || encode(substring(decode(replace(body, ' ', ''), 'hex'), 22, 8), 'hex'))::bit(64)::bigint) ELSE NULL END) AS max_wh,
          min(CASE WHEN split_part(body, ' ', 5) = '00' THEN (('x' || encode(substring(decode(replace(body, ' ', ''), 'hex'), 22, 8), 'hex'))::bit(64)::bigint) ELSE NULL END) AS min_wh
      FROM public.log_rtureceivelog
      WHERE split_part(body, ' ', 5) IN ('00', '39')
      GROUP BY hour, "rtuImei", energy_hex, type_hex, multi_hex;
    `);
    await client.query(`ALTER MATERIALIZED VIEW log_rtureceivelog_hourly SET (timescaledb.materialized_only = false);`);

    // 5. 호환성 일반 뷰 (여기서 KST로 변환하여 출력)
    console.log('호환성 일반 뷰 생성 중...');
    await client.query(`
      CREATE OR REPLACE VIEW public.energy_daily AS 
      SELECT 
          to_char(day AT TIME ZONE 'Asia/Seoul', 'YYYYMMDD') AS ymd, 
          "rtuImei" AS imei, 
          (COALESCE(max_wh, 0) - COALESCE(min_wh, 0)) / 1000.0 AS kwh 
      FROM public.log_rtureceivelog_daily;

      CREATE OR REPLACE VIEW public.energy_hourly AS 
      SELECT 
          hour AT TIME ZONE 'Asia/Seoul' AS ts, 
          "rtuImei" AS imei, 
          (COALESCE(max_wh, 0) - COALESCE(min_wh, 0)) / 1000.0 AS kwh 
      FROM public.log_rtureceivelog_hourly;
    `);

    // 6. 집계 데이터 강제 동기화
    console.log('집계 데이터 동기화 진행 (2025-01-01 ~ 현재)...');
    await client.query(`CALL refresh_continuous_aggregate('log_rtureceivelog_daily', '2025-01-01', NOW());`);
    await client.query(`CALL refresh_continuous_aggregate('log_rtureceivelog_hourly', '2025-01-01', NOW());`);

    // 7. 실시간 분석 뷰 (Materialized View)
    console.log('분석용 뷰(mv_energy_recent) 동기화 중...');
    await client.query(`DROP MATERIALIZED VIEW IF EXISTS public.mv_energy_recent;`);
    const mvQuery = `
      CREATE MATERIALIZED VIEW public.mv_energy_recent AS
      SELECT 
          "rtuImei" AS imei,
          split_part(body, ' ', 4) AS multi_hex,
          MAX(time) AS latest_ts,
          MAX(CASE WHEN split_part(body, ' ', 5) = '00' THEN (('x' || encode(substring(decode(replace(body, ' ', ''), 'hex'), 22, 8), 'hex'))::bit(64)::bigint) ELSE NULL END) AS latest_wh
      FROM public.log_rtureceivelog
      WHERE time >= (NOW() - INTERVAL '1 day')
      GROUP BY imei, multi_hex;
    `;
    await client.query(mvQuery);
    await client.query(`REFRESH MATERIALIZED VIEW public.mv_energy_recent;`);

    console.log('PostgreSQL 전체 동기화 성공 (KST 적용 및 시간대 에러 해결 완료)');
  } catch (err) {
    console.error('DB 초기화 실패:', err.stack);
    throw err;
  } finally {
    client.release();
  }
};

module.exports = { initPostgres };

if (require.main === module) {
  require('dotenv').config();
  initPostgres().then(() => process.exit(0)).catch(() => process.exit(1));
}