const { pool } = require('./db.pg');

const initPostgres = async () => {
  const client = await pool.connect();
  try {
    console.log('PostgreSQL 테이블 및 뷰 동기화 시작...');
    
    await client.query('BEGIN');

    await client.query(`CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;`);

    // 1. 기본 테이블 생성
    await client.query(`
      CREATE TABLE IF NOT EXISTS public.members (
        member_id SERIAL PRIMARY KEY,
        username CHARACTER VARYING(50) NOT NULL UNIQUE,
        password CHARACTER VARYING(255) NOT NULL,
        created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        worker CHARACTER VARYING(100),
        "phoneNumber" CHARACTER VARYING(25),
        is_admin BOOLEAN DEFAULT FALSE
      );

      CREATE TABLE IF NOT EXISTS public.imei_meta (
        imei TEXT PRIMARY KEY,
        address TEXT, sido TEXT, sigungu TEXT,
        lat DOUBLE PRECISION, lon DOUBLE PRECISION,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        energy_hex TEXT, type_hex TEXT, multi_count INTEGER,
        worker TEXT, "phoneNumber" TEXT
      );

      CREATE TABLE IF NOT EXISTS public.facility_info (
        rtuimei TEXT PRIMARY KEY,
        module_capacity TEXT, install_date DATE, monitor_start DATE,
        project_name TEXT, contractor TEXT, as_contact TEXT, image_url TEXT,
        created_by INTEGER REFERENCES public.members(member_id),
        updated_by INTEGER REFERENCES public.members(member_id),
        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS public.facility_maintenance (
        rtuimei TEXT PRIMARY KEY, last_inspection DATE, as_notes TEXT,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS public.facility_maintenance_history (
        id SERIAL PRIMARY KEY, rtuimei TEXT NOT NULL,
        maintenance_date DATE, as_notes TEXT,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS public.energy_nationwide_cache (
        key TEXT PRIMARY KEY, payload JSONB NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS public.django_migrations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        app CHARACTER VARYING(255) NOT NULL,
        name CHARACTER VARYING(255) NOT NULL,
        applied TIMESTAMP WITH TIME ZONE NOT NULL
      );

      CREATE TABLE IF NOT EXISTS public.auth_login_attempts (
        id BIGSERIAL PRIMARY KEY,
        member_id INTEGER REFERENCES public.members(member_id) ON DELETE SET NULL,
        username CHARACTER VARYING(50), success BOOLEAN NOT NULL,
        ip INET, user_agent TEXT, reason TEXT,
        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS public.auth_password_reset (
        id BIGSERIAL PRIMARY KEY,
        member_id BIGINT REFERENCES public.members(member_id) ON DELETE CASCADE,
        token_hash TEXT NOT NULL, expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
        used_at TIMESTAMP WITH TIME ZONE,
        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS public.auth_password_history (
        id SERIAL PRIMARY KEY,
        member_id INTEGER REFERENCES public.members(member_id) ON DELETE CASCADE,
        password_hash TEXT NOT NULL, created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS public.log_rtureceivelog (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
        time TIMESTAMP WITH TIME ZONE NOT NULL,
        "deviceModel" CHARACTER VARYING(5) NOT NULL,
        "msgType" CHARACTER VARYING(1) NOT NULL,
        "seqSendTime" TIME WITHOUT TIME ZONE NOT NULL,
        "businessId" INTEGER, "serviceId" INTEGER,
        "opMode" CHARACTER VARYING(10) NOT NULL,
        "multiId" SMALLINT NOT NULL,
        "bodyLength" INTEGER NOT NULL,
        "bodyOptionId" SMALLINT NOT NULL,
        body TEXT,
        "rtuImei" CHARACTER VARYING(23) NOT NULL
      );

      CREATE TABLE IF NOT EXISTS public.log_remssendlog (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        time TIMESTAMP WITH TIME ZONE NOT NULL,
        "multiId" SMALLINT NOT NULL,
        cid CHARACTER VARYING(25) NOT NULL,
        body TEXT,
        result CHARACTER VARYING(1) NOT NULL,
        error TEXT,
        "rtuImei" CHARACTER VARYING(23) NOT NULL
      );

      CREATE INDEX IF NOT EXISTS "log_remssendlog_cid_42d45c5b" ON public.log_remssendlog (cid);
      CREATE INDEX IF NOT EXISTS "log_remssendlog_rtuImei_38fe98eb" ON public.log_remssendlog ("rtuImei");
      CREATE INDEX IF NOT EXISTS "log_remssendlog_time_84716e9d" ON public.log_remssendlog ("time");
    `);

    await client.query('COMMIT');
    console.log('기본 테이블 생성 및 설정 완료.');

    // 2. 하이퍼테이블 설정
    try {
      await client.query(`SELECT create_hypertable('public.log_rtureceivelog', 'time', if_not_exists => TRUE);`);
      await client.query(`SELECT create_hypertable('public.log_remssendlog', 'time', if_not_exists => TRUE);`);
      console.log('하이퍼테이블 설정 완료.');
    } catch (e) {
      console.log('하이퍼테이블 설정 건너뜀 (이미 존재함).');
    }

    // 3. 일일 집계 뷰 (Daily)
    const { rows: dailyExists } = await client.query(`
      SELECT 1 FROM timescaledb_information.continuous_aggregates WHERE view_name = 'log_rtureceivelog_daily'
    `);

    if (dailyExists.length === 0) {
      console.log('지속적 집계 뷰(Daily) 생성 중...');
      await client.query(`
        CREATE MATERIALIZED VIEW log_rtureceivelog_daily
        WITH (timescaledb.continuous) AS
        SELECT 
            time_bucket('1 day', "time") AS day,
            "rtuImei",
            split_part(body, ' ', 2) AS energy_hex,
            split_part(body, ' ', 3) AS type_hex,
            split_part(body, ' ', 4) AS multi_hex,
            max(CASE WHEN split_part(body, ' ', 5) = '00' THEN (('x' || encode(substring(decode(replace(body, ' ', ''), 'hex'), 22, 8), 'hex'))::bit(64)::bigint) ELSE NULL END) AS max_wh,
            min(CASE WHEN split_part(body, ' ', 5) = '00' THEN (('x' || encode(substring(decode(replace(body, ' ', ''), 'hex'), 22, 8), 'hex'))::bit(64)::bigint) ELSE NULL END) AS min_wh
        FROM public.log_rtureceivelog
        WHERE split_part(body, ' ', 5) IN ('00', '39')
        GROUP BY day, "rtuImei", energy_hex, type_hex, multi_hex;
      `);
      await client.query(`ALTER MATERIALIZED VIEW log_rtureceivelog_daily SET (timescaledb.materialized_only = false);`);
      console.log('지속적 집계 뷰(Daily) 생성 완료');
    }

    // 4. [수정 포인트] 시간 단위 집계 뷰 (Hourly) 추가
    const { rows: hourlyExists } = await client.query(`
      SELECT 1 FROM timescaledb_information.continuous_aggregates WHERE view_name = 'log_rtureceivelog_hourly'
    `);

    if (hourlyExists.length === 0) {
      console.log('지속적 집계 뷰(Hourly) 생성 중...');
      await client.query(`
        CREATE MATERIALIZED VIEW log_rtureceivelog_hourly
        WITH (timescaledb.continuous) AS
        SELECT 
            time_bucket('1 hour', "time") AS hour,
            "rtuImei",
            split_part(body, ' ', 2) AS energy_hex,
            split_part(body, ' ', 3) AS type_hex,
            split_part(body, ' ', 4) AS multi_hex,
            max(CASE WHEN split_part(body, ' ', 5) = '00' THEN (('x' || encode(substring(decode(replace(body, ' ', ''), 'hex'), 22, 8), 'hex'))::bit(64)::bigint) ELSE NULL END) AS max_wh,
            min(CASE WHEN split_part(body, ' ', 5) = '00' THEN (('x' || encode(substring(decode(replace(body, ' ', ''), 'hex'), 22, 8), 'hex'))::bit(64)::bigint) ELSE NULL END) AS min_wh
        FROM public.log_rtureceivelog
        WHERE split_part(body, ' ', 5) IN ('00', '39')
        GROUP BY hour, "rtuImei", energy_hex, type_hex, multi_hex;
      `);
      await client.query(`ALTER MATERIALIZED VIEW log_rtureceivelog_hourly SET (timescaledb.materialized_only = false);`);
      console.log('지속적 집계 뷰(Hourly) 생성 완료');
    }

    // 5. 호환성 뷰 (energy_daily, energy_hourly)
    console.log('호환성 일반 뷰 동기화 중...');
    await client.query(`
      CREATE OR REPLACE VIEW public.energy_daily AS 
      SELECT 
          to_char(day, 'YYYYMMDD') AS ymd, 
          "rtuImei" AS imei, 
          (COALESCE(max_wh, 0) - COALESCE(min_wh, 0)) / 1000.0 AS kwh 
      FROM public.log_rtureceivelog_daily;

      -- [수정] 이제 energy_hourly는 시간 단위 집계 뷰를 직접 참조합니다.
      CREATE OR REPLACE VIEW public.energy_hourly AS 
      SELECT 
          hour AS ts, 
          "rtuImei" AS imei, 
          (COALESCE(max_wh, 0) - COALESCE(min_wh, 0)) / 1000.0 AS kwh 
      FROM public.log_rtureceivelog_hourly;
    `);
    console.log('호환성 일반 뷰 생성 완료');

    // 6. [핵심] 더미 데이터 입력 후 즉시 반영을 위한 강제 동기화
    console.log('집계 데이터 강제 동기화 중 (2025~현재)...');
    await client.query(`CALL refresh_continuous_aggregate('log_rtureceivelog_daily', '2025-01-01', NOW());`);
    await client.query(`CALL refresh_continuous_aggregate('log_rtureceivelog_hourly', '2025-01-01', NOW());`);

    // 7. 최근 에너지 분석 뷰 (Materialized View)
    const { rows: mvExists } = await client.query(`
      SELECT 1 FROM pg_matviews WHERE matviewname = 'mv_energy_recent'
    `);

    if (mvExists.length === 0) {
      console.log('최근 에너지 분석 뷰(mv_energy_recent) 생성 중...');
      const mvQuery = `
        CREATE MATERIALIZED VIEW public.mv_energy_recent AS
        WITH raw0 AS (
            SELECT log_rtureceivelog."time" AS ts,
                   log_rtureceivelog."rtuImei" AS imei,
                   regexp_replace(log_rtureceivelog.body, '[^0-9A-Fa-f]'::text, ''::text, 'g'::text) AS clean_hex0
            FROM log_rtureceivelog
            WHERE ((log_rtureceivelog.body IS NOT NULL) AND (log_rtureceivelog."rtuImei" IS NOT NULL) AND (log_rtureceivelog."time" >= (now() - '00:05:00'::interval)))
        ), raw1 AS (
            SELECT raw0.ts, raw0.imei,
                   CASE WHEN ((length(raw0.clean_hex0) % 2) = 1) THEN ('0'::text || raw0.clean_hex0) ELSE raw0.clean_hex0 END AS clean_hex
            FROM raw0 WHERE (length(raw0.clean_hex0) >= 10)
        ), hdr AS (
            SELECT raw1.ts, raw1.imei, decode(raw1.clean_hex, 'hex'::text) AS b,
                   octet_length(decode(raw1.clean_hex, 'hex'::text)) AS len,
                   get_byte(decode(raw1.clean_hex, 'hex'::text), 0) AS cmd,
                   get_byte(decode(raw1.clean_hex, 'hex'::text), 1) AS energy,
                   get_byte(decode(raw1.clean_hex, 'hex'::text), 2) AS type,
                   get_byte(decode(raw1.clean_hex, 'hex'::text), 3) AS multi,
                   get_byte(decode(raw1.clean_hex, 'hex'::text), 4) AS err, 5 AS data_off
            FROM raw1 WHERE (SUBSTRING(raw1.clean_hex FROM 1 FOR 2) = '14'::text)
        ), pv_single AS (
            SELECT hdr.ts, hdr.imei, hdr.multi,
                   (((((((((get_byte(hdr.b, (hdr.data_off + 18)))::numeric * ('72057594037927936'::bigint)::numeric) + ((get_byte(hdr.b, (hdr.data_off + 19)))::numeric * ('281474976710656'::bigint)::numeric)) + ((get_byte(hdr.b, (hdr.data_off + 20)))::numeric * ('1099511627776'::bigint)::numeric)) + ((get_byte(hdr.b, (hdr.data_off + 21)))::numeric * ('4294967296'::bigint)::numeric)) + ((get_byte(hdr.b, (hdr.data_off + 22)))::numeric * (16777216)::numeric)) + ((get_byte(hdr.b, (hdr.data_off + 23)))::numeric * (65536)::numeric)) + ((get_byte(hdr.b, (hdr.data_off + 24)))::numeric * (256)::numeric)) + (get_byte(hdr.b, (hdr.data_off + 25)))::numeric) AS cum_wh
            FROM hdr WHERE ((hdr.err = 0) AND (hdr.energy = 1) AND (hdr.type = 1) AND (hdr.len >= (hdr.data_off + 26)))
        ), pv_three AS (
            SELECT hdr.ts, hdr.imei, hdr.multi,
                   (((((((((get_byte(hdr.b, (hdr.data_off + 28)))::numeric * ('72057594037927936'::bigint)::numeric) + ((get_byte(hdr.b, (hdr.data_off + 29)))::numeric * ('281474976710656'::bigint)::numeric)) + ((get_byte(hdr.b, (hdr.data_off + 30)))::numeric * ('1099511627776'::bigint)::numeric)) + ((get_byte(hdr.b, (hdr.data_off + 31)))::numeric * ('4294967296'::bigint)::numeric)) + ((get_byte(hdr.b, (hdr.data_off + 32)))::numeric * (16777216)::numeric)) + ((get_byte(hdr.b, (hdr.data_off + 33)))::numeric * (65536)::numeric)) + ((get_byte(hdr.b, (hdr.data_off + 34)))::numeric * (256)::numeric)) + (get_byte(hdr.b, (hdr.data_off + 35)))::numeric) AS cum_wh
            FROM hdr WHERE ((hdr.err = 0) AND (hdr.energy = 1) AND (hdr.type = 2) AND (hdr.len >= (hdr.data_off + 38)))
        ), pv AS (
            SELECT ts, imei, multi, cum_wh FROM pv_single UNION ALL SELECT ts, imei, multi, cum_wh FROM pv_three
        ), th AS (
            SELECT hdr.ts, hdr.imei, hdr.multi,
                   ((((((((((get_byte(hdr.b, (hdr.data_off + 28)))::numeric * ('72057594037927936'::bigint)::numeric) + ((get_byte(hdr.b, (hdr.data_off + 29)))::numeric * ('281474976710656'::bigint)::numeric)) + ((get_byte(hdr.b, (hdr.data_off + 30)))::numeric * ('1099511627776'::bigint)::numeric)) + ((get_byte(hdr.b, (hdr.data_off + 31)))::numeric * ('4294967296'::bigint)::numeric)) + ((get_byte(hdr.b, (hdr.data_off + 32)))::numeric * (16777216)::numeric)) + ((get_byte(hdr.b, (hdr.data_off + 33)))::numeric * (65536)::numeric)) + ((get_byte(hdr.b, (hdr.data_off + 34)))::numeric * (256)::numeric)) + (get_byte(hdr.b, (hdr.data_off + 35)))::numeric) / 860.42065) AS cum_kwh
            FROM hdr WHERE ((hdr.err = 0) AND (hdr.energy = 2) AND (hdr.len >= (hdr.data_off + 38)))
        ), pv_dev AS (
            SELECT imei, multi, min(cum_wh) AS min_recent, max(cum_wh) AS max_recent FROM pv GROUP BY imei, multi
        ), th_dev AS (
            SELECT imei, multi, min(cum_kwh) AS min_recent, max(cum_kwh) AS max_recent FROM th GROUP BY imei, multi
        )
        SELECT imei, multi, min_recent, max_recent FROM pv_dev
        UNION ALL
        SELECT imei, multi, min_recent, max_recent FROM th_dev
        WITH NO DATA;
      `;
      await client.query(mvQuery);
    }
    
    // 분석 뷰 무조건 리프레시
    await client.query(`REFRESH MATERIALIZED VIEW public.mv_energy_recent;`);

    console.log('PostgreSQL 전체 동기화 성공');
  } catch (err) {
    try { await client.query('ROLLBACK'); } catch (e) {}
    console.error('DB 초기화 실패:', err.message);
    throw err;
  } finally {
    client.release();
  }
};

module.exports = { initPostgres };

if (require.main === module) {
  require('dotenv').config();
  initPostgres().then(() => process.exit(0)).catch(() => process.exit(1));
}